import { DashboardIcon, AnalyticsIcon, MenuBarIcon,JournalIcon,BookPublicationIcon,BookChapterIcon,CaseStudyIcon,ResearchSeminarIcon,
	EContentICon,ResearchAwardIcon,ConferenceIcon,PatentIcon,ResearchProjectIcon,IprIcon,FacultyIcon,EditedBookIcon,
	MeetingStakeholderIcon,AuthorIcon,ResearchIcon,TeachMeetBrandIcon,PublicationIcon,TeachingIcon,BrandingIcon,ApprovalIcon
} from './layout';
import {
	ArrowIcon,
	SortArrowIcon,
	ActionIcon,
	PlusIcon,
	PenIcon,
	DraftIcon,
	OpenBookIcon,
	SearchIcon,
	SelectDateIcon,
	XIcon,
	CampusIcon,
	DownloadIcon,
	AttendanceIcon,
	SuccessIcon,
	DeleteIcon,
	MinusIcon,
	EyeIcon,
	CloseEyeIcon,
	PreviewIcon,
	SignOutIcon,
	RightIcon
} from './base';
import { MeetingIcon, ScheduledIcon } from './modules';

export {
	DashboardIcon,
	ArrowIcon,
	AnalyticsIcon,
	SortArrowIcon,
	ActionIcon,
	MenuBarIcon,
	PlusIcon,
	MeetingIcon,
	ScheduledIcon,
	PenIcon,
	DraftIcon,
	OpenBookIcon,
	SearchIcon,
	SelectDateIcon,
	XIcon,
	CampusIcon,
	DownloadIcon,
	AttendanceIcon,
	SuccessIcon,
	DeleteIcon,
	MinusIcon,
	EyeIcon,
	CloseEyeIcon,
	PreviewIcon,
	JournalIcon,
	BookPublicationIcon,
	BookChapterIcon,
	CaseStudyIcon,
	ResearchSeminarIcon,
	EContentICon,
	ResearchAwardIcon,
	SignOutIcon,
	ConferenceIcon,
	PatentIcon,
	ResearchProjectIcon,
	IprIcon,
	FacultyIcon,
	EditedBookIcon,
	MeetingStakeholderIcon,
	AuthorIcon,
	ResearchIcon,
	TeachMeetBrandIcon,
	PublicationIcon,
	TeachingIcon,
	BrandingIcon,
	ApprovalIcon
};
